import {useState} from 'react';
import {Link,useNavigate,useLocation} from 'react-router-dom';
import {GitBranch,CheckCircle2} from 'lucide-react';
import {useAuth} from '../context/AuthContext.jsx';
import {api,errorMessage} from '../lib/api.js';
import {Field,Notice,Submit} from '../components/UI.jsx';
export default function Auth({register=false}) {
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const {login}=useAuth();const navigate=useNavigate();const location=useLocation();
  async function submit(event){event.preventDefault();setError('');setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget));try{if(register){await api.post('/auth/register',values);navigate('/login',{state:{registered:true}});}else{await login(values);navigate('/projects');}}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <div className="auth-layout"><section className="auth-story"><Link className="brand" to="/"><GitBranch/>RootTrace</Link><div><div className="eyebrow">FROM INCIDENT TO INSIGHT</div><h1>Find the cause.<br/>Follow the evidence.</h1><p>A focused workspace for investigating backend failures with your logs, runbooks, and engineering knowledge.</p><ul><li><CheckCircle2/> Project-isolated evidence</li><li><CheckCircle2/> Traceable source citations</li><li><CheckCircle2/> Clear, structured reports</li></ul></div><small>Built for developers who need answers they can verify.</small></section><main className="auth-form"><div className="auth-form-inner"><div className="eyebrow">YOUR ENGINEERING WORKSPACE</div><h1>{register?'Create your account':'Welcome back'}</h1><p>{register?'Start investigating with evidence you control.':'Sign in to continue your investigations.'}</p>{location.state?.registered&&<div className="success" role="status">Account created. You can now sign in.</div>}<Notice>{error}</Notice><form onSubmit={submit}>{register&&<Field label="Full name"><input name="name" autoComplete="name" required minLength={2} maxLength={80}/></Field>}<Field label="Email address"><input type="email" name="email" autoComplete="email" required maxLength={254}/></Field><Field label="Password" hint={register?'At least 10 characters.':''}><input type="password" name="password" autoComplete={register?'new-password':'current-password'} required minLength={10} maxLength={72}/></Field><Submit busy={busy}>{register?'Create account':'Sign in'}</Submit></form><p className="auth-switch">{register?'Already have an account?':'New to RootTrace?'} <Link to={register?'/login':'/register'}>{register?'Sign in':'Create an account'}</Link></p></div></main></div>;
}
